### ISSUE TITLE
Offer to take over development

### ISSUE THREAD

**Issue by djmango** [totobest/BlackMarket#2]
Not sure where to place this, but the original mod owner said that you too have given up on development/maintenance of this mod? If it's okay by you, I offer to take over development and maintenance, (I use this mod a lot and am looking to get into factorio mod/FOSS development)

**Comment by Kite1024** [comment]
Hey djmango,

I'm not the owner of the mod but I did notice that the licence is the following:
https://creativecommons.org/licenses/by-nc/4.0/
(see root folder of the mod for the license file)

This means that you're free to adapt and distribute the source as you see fit, as long as you attribute the original creator (I believe that a link to the original repo would do exactly that).

I'd personally be pretty psyched it this mod was updated tot the latest experimental :)

**Comment by djmango** [comment]
I've forked the mod, and will do my best to maintain it.
https://mods.factorio.com/mod/BlackMarket2
https://github.com/djmango/BlackMarket2
